// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Threading;
using Microsoft.Extensions.Logging;

namespace TrackSeries.TheTVDB.HealthCheck.Properties
{
    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("TrackSeries.TheTVDB.HealthCheck.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        ///     SearchTerm must not be null or empty when CheckSearch is enabled.
        /// </summary>
        public static string InvalidSearchTerm
            => GetString("InvalidSearchTerm");

        /// <summary>
        ///     SerieId must be greater than 0 when CheckSeries is enabled.
        /// </summary>
        public static string InvalidSerieId
            => GetString("InvalidSerieId");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

namespace TrackSeries.TheTVDB.HealthCheck.Properties.Internal
{
    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("TrackSeries.TheTVDB.HealthCheck.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
    }
}
